/**
 * Auto-generated TypeScript types from Directus Schema
 * Generated from current-schema.json
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

import { DirectusClient } from '@directus/sdk';

// =============================================================================
// COLLECTION INTERFACES
// =============================================================================

export interface DirectusCategories {
  id?: string;
  title?: string | null;
  slug?: string | null;
  image?: string | null; // UUID of image file
  date_created?: string;
  date_updated?: string;
}

export interface DirectusContacts {
  id?: string;
  email?: string | null;
  phone?: string | null;
  date_created?: string;
  date_updated?: string;
}

export interface DirectusFooterMenu {
  id?: string;
  title?: string | null;
  links?: any | null; // JSON array of links
  date_created?: string;
  date_updated?: string;
}

export interface DirectusHeaderMenu {
  id?: string;
  title?: string | null;
  link?: string | null;
  sub_menu?: any | null; // JSON array of submenu items
  date_created?: string;
  date_updated?: string;
}

export interface DirectusHero {
  id?: string;
  title?: string | null;
  subtitle?: string | null;
  primary_button_text?: string | null;
  primary_button_link?: string | null;
  date_created?: string;
  date_updated?: string;
}

export interface DirectusNews {
  id?: string;
  title?: string | null;
  content?: string | null;
  image?: string | null; // UUID of image file
  published_date?: string | null;
  date_created?: string;
  date_updated?: string;
}

export interface DirectusPages {
  id?: string;
  title?: string | null;
  slug?: string | null;
  content?: any | null; // JSON content blocks
  date_created?: string;
  date_updated?: string;
}

export interface DirectusServices {
  id?: string;
  title?: string | null;
  description?: string | null;
  slug?: string | null;
  date_created?: string;
  date_updated?: string;
}

export interface DirectusSettings {
  id?: string;
  site_title?: string | null;
  site_description?: string | null;
  date_created?: string;
  date_updated?: string;
}

export interface DirectusSubMenuContent {
  id?: string;
  slug: string;
  category: 'loja' | 'servicos' | 'suporte';
  title: string;
  description?: string | null;
  content?: any | null; // HTML content
  featured_image?: string | null; // UUID of image file
  status: 'draft' | 'published' | 'archived';
  sort?: number | null;
  date_created?: string;
  date_updated?: string;
}

// =============================================================================
// MAIN SCHEMA TYPE
// =============================================================================

export interface DirectusSchema {
  categories: DirectusCategories[];
  contacts: DirectusContacts[];
  footer_menu: DirectusFooterMenu[];
  header_menu: DirectusHeaderMenu[];
  hero: DirectusHero; // singleton
  news: DirectusNews[];
  pages: DirectusPages[];
  services: DirectusServices[];
  settings: DirectusSettings; // singleton
  sub_menu_content: DirectusSubMenuContent[];
}

// =============================================================================
// UTILITY TYPES
// =============================================================================

export type DirectusItem<T extends keyof DirectusSchema> = DirectusSchema[T] extends (infer U)[] ? U : DirectusSchema[T];
export type DirectusCollectionItems<T extends keyof DirectusSchema> = DirectusSchema[T];
export type DirectusSingleton<T extends keyof DirectusSchema> = DirectusSchema[T];

// Status types commonly used
export type DirectusStatus = 'draft' | 'published' | 'archived';

// Common field types
export interface DirectusFile {
  id: string;
  title: string;
  filename_disk: string;
  filename_download: string;
  type: string;
  filesize: number;
  width: number;
  height: number;
}

// Sub-menu categories
export type SubMenuCategory = 'loja' | 'servicos' | 'suporte';

// =============================================================================
// API HELPERS
// =============================================================================

export interface DirectusApiHelpers {
  // Generic helpers for working with collections
  getCollectionItems: <T extends keyof DirectusSchema>(
    collection: T,
    query?: any
  ) => Promise<DirectusCollectionItems<T>>;
  
  getSingleton: <T extends keyof DirectusSchema>(
    collection: T
  ) => Promise<DirectusSingleton<T>>;
  
  getItemById: <T extends keyof DirectusSchema>(
    collection: T,
    id: string
  ) => Promise<DirectusItem<T>>;
  
  getItemBySlug: <T extends keyof DirectusSchema>(
    collection: T,
    slugField: string,
    slug: string
  ) => Promise<DirectusItem<T> | null>;
}

// =============================================================================
// SPECIFIC QUERY HELPERS
// =============================================================================

export interface DirectusQueries {
  // Header Menu
  getHeaderMenu: () => Promise<DirectusHeaderMenu[]>;
  
  // Footer Menu  
  getFooterMenu: () => Promise<DirectusFooterMenu[]>;
  
  // Hero Section
  getHero: () => Promise<DirectusHero>;
  
  // Services
  getServices: (publishedOnly?: boolean) => Promise<DirectusServices[]>;
  getServiceBySlug: (slug: string) => Promise<DirectusServices | null>;
  
  // Categories
  getCategories: () => Promise<DirectusCategories[]>;
  getCategoryBySlug: (slug: string) => Promise<DirectusCategories | null>;
  
  // Sub Menu Content
  getSubMenuContent: (category?: SubMenuCategory, publishedOnly?: boolean) => Promise<DirectusSubMenuContent[]>;
  getSubMenuContentBySlug: (slug: string) => Promise<DirectusSubMenuContent | null>;
  
  // Pages
  getPages: (publishedOnly?: boolean) => Promise<DirectusPages[]>;
  getPageBySlug: (slug: string) => Promise<DirectusPages | null>;
  
  // News
  getNews: (limit?: number) => Promise<DirectusNews[]>;
  getNewsById: (id: string) => Promise<DirectusNews | null>;
  
  // Settings
  getSettings: () => Promise<DirectusSettings>;
}

// =============================================================================
// TYPE GUARDS
// =============================================================================

export function isPublished<T extends { status?: string }>(item: T): boolean {
  return item.status === 'published';
}

export function isDraft<T extends { status?: string }>(item: T): boolean {
  return item.status === 'draft';
}

export function isArchived<T extends { status?: string }>(item: T): boolean {
  return item.status === 'archived';
}

// =============================================================================
// FORM VALIDATION SCHEMAS (for React Hook Form + Zod)
// =============================================================================

export interface DirectusValidationSchemas {
  subMenuContent: {
    slug: string;
    category: SubMenuCategory;
    title: string;
    description?: string;
    content?: any;
    status: 'draft' | 'published' | 'archived';
  };
  
  service: {
    title: string;
    description?: string;
    slug: string;
  };
  
  page: {
    title: string;
    slug: string;
    content?: any;
  };
  
  news: {
    title: string;
    content?: string;
    published_date?: string;
  };
}