name: React Frontend CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
  repository_dispatch:
    types: [directus-update]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linting
        run: bun run lint || echo "No linting configured"

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Build project
        run: bun run build
        env:
          VITE_DIRECTUS_URL: ${{ secrets.VITE_DIRECTUS_URL }}
          VITE_DIRECTUS_TOKEN: ${{ secrets.VITE_DIRECTUS_TOKEN }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: dist

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: dist
      
      - name: Deploy to staging server
        uses: appleboy/scp-action@master
        with:
          host: "${{ secrets.STAGING_HOST }}"
          username: "${{ secrets.STAGING_USERNAME }}"
          key: "${{ secrets.STAGING_SSH_KEY }}"
          source: "dist/*"
          target: "${{ secrets.STAGING_TARGET_PATH }}"
          strip_components: 1

  deploy-production:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: dist
      
      - name: Deploy to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          source: "dist/*"
          target: ${{ secrets.PRODUCTION_TARGET_PATH }}
          strip_components: 1
