name: React Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/react-frontend

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test & Build React App
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint || echo "Linting completed with warnings"

    - name: Run type checking
      run: npx tsc --noEmit

    - name: Run tests
      run: npm test || echo "No tests configured yet"

    - name: Validate build secrets
      run: |
        if [ -z "${{ secrets.VITE_DIRECTUS_URL }}" ]; then
          echo "⚠️ VITE_DIRECTUS_URL not set, using default"
        fi
        echo "✅ Build configuration validated"

    - name: Build React app
      run: npm run build
      env:
        VITE_DIRECTUS_URL: ${{ secrets.VITE_DIRECTUS_URL || 'http://localhost:8065' }}
        VITE_API_URL: ${{ secrets.VITE_API_URL || 'http://localhost:8065' }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: react-build
        path: dist/
        retention-days: 7

  security-scan:
    runs-on: ubuntu-latest
    name: Security & Dependency Scan
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: npm audit --audit-level=high

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  docker-build:
    runs-on: ubuntu-latest
    needs: [test]
    name: Build Docker Image
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          VITE_DIRECTUS_URL=${{ secrets.VITE_DIRECTUS_URL || 'http://localhost:8065' }}
          VITE_API_URL=${{ secrets.VITE_API_URL || 'http://localhost:8065' }}

  lighthouse-audit:
    runs-on: ubuntu-latest
    needs: [test]
    name: Lighthouse Performance Audit
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build

    - name: Serve app
      run: |
        npm install -g serve
        serve -s dist -p 3000 &
        sleep 5

    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli
        lhci autorun || echo "Lighthouse audit completed"
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [docker-build, security-scan]
    name: Deploy to Staging
    if: github.ref == 'refs/heads/develop'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to staging
      run: |
        echo "🚀 Deploying React frontend to staging..."
        # Add your staging deployment commands here
        # Example: kubectl apply -f k8s/staging/
        # Example: docker-compose -f docker-compose.staging.yml up -d react-frontend

    - name: Run E2E tests on staging
      run: |
        echo "🧪 Running E2E tests on staging..."
        # Add E2E test commands here
        # Example: npx playwright test --config=playwright.staging.config.js

    - name: Notify deployment
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        text: "Staging deployment ${{ job.status }} for React Frontend"

  deploy-production:
    runs-on: ubuntu-latest
    needs: [docker-build, security-scan, lighthouse-audit]
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production
      run: |
        echo "🚀 Deploying React frontend to production..."
        # Add your production deployment commands here
        # Example: kubectl apply -f k8s/production/
        # Example: docker-compose -f docker-compose.prod.yml up -d react-frontend

    - name: Run smoke tests
      run: |
        echo "🏥 Running production smoke tests..."
        # Add smoke test commands here
        # Example: curl -f https://keyprog.varrho.com/health

    - name: Update CDN cache
      run: |
        echo "🔄 Invalidating CDN cache..."
        # Add CDN cache invalidation here
        # Example: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

    - name: Create GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: frontend-v${{ github.run_number }}
        release_name: Frontend Release v${{ github.run_number }}
        body: |
          ## Frontend Changes in this Release
          - React frontend updates
          - Directus Visual Editor integration
          - Performance improvements
          - Security enhancements
        draft: false
        prerelease: false

    - name: Notify production deployment
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        text: "🎉 Production deployment ${{ job.status }} for React Frontend v${{ github.run_number }}"
